export interface Eeff {
  id: string;
  ruc?: string | null;
  razon_social?: string | null;
  anio_reporte?: number | null;
  activo_efectivo_y_equivalentes_de_efectivo?: number | null;
  activo_inversiones_financieras?: number | null;
  activo_ctas_por_cobrar_comerciales_terceros?: number | null;
  activo_ctas_por_cobrar_comerciales_relacionadas?: number | null;
  activo_cuentas_por_cobrar_al_personal_socios_y_directores?: number | null;
  activo_ctas_por_cobrar_diversas_terceros?: number | null;
  activo_ctas_por_cobrar_diversas_relacionadas?: number | null;
  activo_serv_y_otros_contratados_por_anticipado?: number | null;
  activo_estimacion_ctas_de_cobranza_dudosa?: number | null;
  activo_mercaderias?: number | null;
  activo_productos_terminados?: number | null;
  activo_subproductos_desechos_y_desperdicios?: number | null;
  activo_productos_en_proceso?: number | null;
  activo_materias_primas?: number | null;
  activo_materiales_aux_suministros_y_repuestos?: number | null;
  activo_envases_y_embalajes?: number | null;
  activo_inventarios_por_recibir?: number | null;
  activo_desvalorizacion_de_inventarios?: number | null;
  activo_activos_no_ctes_mantenidos_para_la_venta?: number | null;
  activo_otro_activos_corrientes?: number | null;
  activo_inversiones_mobiliarias?: number | null;
  activo_propiedades_de_inversion?: number | null;
  activo_activos_por_derecho_de_uso?: number | null;
  activo_propiedades_planta_y_equipo?: number | null;
  activo_depreciacion_de_1_2_y_ppe_acumulados?: number | null;
  activo_intangibles?: number | null;
  activo_activos_biologicos?: number | null;
  activo_deprec_act_biologico_y_amortiz_acumulada?: number | null;
  activo_desvalorizacion_de_activo_inmovilizado?: number | null;
  activo_activo_diferido?: number | null;
  activo_otros_activos_no_corrientes?: number | null;
  activo_total_activo_neto?: number | null;
  pasivo_sobregiros_bancarios?: number | null;
  pasivo_trib_y_aport_sist_pens_y_salud_por_pagar?: number | null;
  pasivo_remuneraciones_y_participaciones_por_pagar?: number | null;
  pasivo_ctas_por_pagar_comerciales_terceros?: number | null;
  pasivo_ctas_por_pagar_comerciales_relacionadas?: number | null;
  pasivo_ctas_por_pagar_accionistas_socios_participantes_y_direct?: number | null;
  pasivo_ctas_por_pagar_diversas_terceros?: number | null;
  pasivo_ctas_por_pagar_diversas_relacionadas?: number | null;
  pasivo_obligaciones_financieras?: number | null;
  pasivo_provisiones?: number | null;
  pasivo_pasivo_diferido?: number | null;
  pasivo_total_pasivo?: number | null;
  patrimonio_capital?: number | null;
  patrimonio_acciones_de_inversion?: number | null;
  patrimonio_capital_adicional_positivo?: number | null;
  patrimonio_capital_adicional_negativo?: number | null;
  patrimonio_resultados_no_realizados?: number | null;
  patrimonio_excedente_de_revaluacion?: number | null;
  patrimonio_reservas?: number | null;
  patrimonio_resultados_acumulados_positivos?: number | null;
  patrimonio_resultados_acumulados_negativos?: number | null;
  patrimonio_utilidad_de_ejercicio?: number | null;
  patrimonio_perdida_de_ejercicio?: number | null;
  patrimonio_total_patrimonio?: number | null;
  patrimonio_total_pasivo_y_patrimonio?: number | null;
  created_at?: string;
  updated_at?: string;
}

export type CreateEeffDto = Omit<Eeff, 'id' | 'created_at' | 'updated_at'>;
export type UpdateEeffDto = Partial<CreateEeffDto>;