// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kjeprmbqwtzeadtfrxie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZXBybWJxd3R6ZWFkdGZyeGllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDM3NTEsImV4cCI6MjA3MzAxOTc1MX0.WeQF5C0hmjmRcZu8ZTwKWuuFuw_we3eR3eYf-Zrx1nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);